const DEFAULT_BINGO_CALLS = [
  "Kelly's Eye",
  "One Little Duck",
  "Cup of Tea",
  "Knock at the Door",
  "Man Alive",
  "Half a Dozen",
  "Lucky Seven",
  "Garden Gate",
  "Doctor’s Orders",
  "All the 10s",
  "Legs Eleven",
  "One Dozen",
  "Unlucky for Some",
  "Valentine’s Day",
  "Young and Keen",
  "Sweet Sixteen",
  "Dancing Queen",
  "Coming of Age",
  "Goodbye, Terry",
  "One Score",
  "Rising Star",
  "Dancing Shoes",
  "Lucky Number",
  "Great Shape",
  "Quarter Century",
  "Going Strong",
  "Family Time",
  "Over the Moon",
  "Looking Fine",
  "Prime Time",
  "Dirty Thirty",
  "Buckle My Shoe",
  "All the Threes",
  "Ask for More",
  "Jump and Jive",
  "Three Dozen",
  "More than One",
  "Christmas Cake",
  "Prime of Your Life",
  "Naughty Forty",
  "Tickle Me",
  "Danny La Rue",
  "Over the Hill",
  "Clean the Floor",
  "Snakes Alive",
  "Up to Tricks",
  "Four and Seven",
  "Four Dozen",
  "PC",
  "Half a Century",
  "Tickle Me",
  "Danny La Rue",
  "Over the Hill",
  "Clean the Floor",
  "Snakes Alive",
  "Getting Started",
  "Let's Go!",
  "Up and Running",
  "Bright Lights",
  "Full Speed Ahead",
  "Baker's Dozen",
  "Turn the Screw",
  "Tickle Me",
  "Red Raw",
  "Old Age",
  "Clickety Click",
  "Stairway to Heaven",
  "Save the Date",
  "Get a Room",
  "Three Score",
  "All the Sevens",
  "72 for You",
  "Lucky for Some",
  "Dance the Night Away",
  "Strive for 75",
  "Shining Bright",
  "Lucky Charm",
  "Peaceful Mind",
  "In the Mood",
  "Forty Forever",
  "Let’s Have Fun",
  "Dance All Night",
  "In the Moment",
  "Color Me Happy",
  "Feeling Good",
  "Between the sticks",
  "Torquay in Devon",
  "Two Fat Ladies",
  "Nearly There",
  "Top of the Shop",
];

export default DEFAULT_BINGO_CALLS;
